[package]
name = "big_int_stuff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
const_fn_assert = "0.1.2"
rand = "0.8"

[features]
default-features=[]
karatsuba=[]
